import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ProviderRedux from '@/redux/ProviderRedux'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderRedux>
        <main>
        {children}
        </main>
        </ProviderRedux>
      </body>
    </html>
  )
}
